version: '3.7'

services: 
    bot:
        image: squirrelnet/nebula
        networks: 
            - bot_net
        volumes:
            - bot_data:/opt/data:rw
        environment: 
            BOT_API: $BOT_API
            BOT_USER: $BOT_USER
            BOT_NAME: $BOT_NAME
            AUTHOR: $AUTHOR
            VERSION: $VERSION
            SOURCE: $REPOSITORY_URL

            STAFF_GROUP: $STAFF_GROUP
            ADMIN_ID: $ADMIN_ID
            OWNER: $OWNER
            LOG_CHANNEL: $LOG_CHANNEL

            YANDEX_API: $YANDEX_API
            OPENWEATHER_API: $OPENWEATHER_API

            DATABASE_SERVER: $DATABASE_SERVER
            DATABASE_NAME: $DATABASE_NAME
            DATABASE_USERNAME: $DATABASE_USERNAME
            DATABASE_PASSWORD: $DATABASE_PASSWORD

    bot_agent:
        image: squirrelnet/nebula-agent
        networks: 
            - bot_net
        volumes:
            - bot_data:/opt/data:rw
            - ../:/opt/data/local:rw
        environment: 
            SSH_PASSWORD: $AGENT_SSH_PASSWORD
            #REPOSITORY_URL: $REPOSITORY_URL
            #REPOSITORY_BRANCH: $REPOSITORY_BRANCH
            REPOSITORY_VOLUME: /opt/data/local
            DEBUG: enable

networks:
    bot_net:

volumes:
    bot_data: